name: Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm run ci
